# For changed dependencies
📦 dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - pnpm-lock.yaml

# For icons changes
🎨 icons:
  - changed-files:
      - any-glob-to-any-file:
          - 'icons/**/*.svg'
