packages:
  - "packages/*"
  - "test/*"
allowBuilds:
  '@parcel/watcher': false
  canvas: true
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  sharp: true
  svelte-preprocess: true
  ttf2woff2: true
catalog:
  typescript: 6.0.3
  astro: ^7.1.1
  vite: ^8.1.5
  vitest: ^4.1.10
  jest-serializer-html: ^7.1.0
  jsdom: 27.4.0
  "@testing-library/jest-dom": 6.9.1
  rollup: 4.62.2
  "@rollup/plugin-node-resolve": 16.0.3
  rollup-plugin-dts: 6.4.1
  rollup-plugin-esbuild: 6.2.1
  rollup-plugin-filesize: 10.0.0
  rollup-plugin-license: 3.7.1
  rollup-plugin-peer-deps-external: 2.2.4
  rollup-plugin-visualizer: ^7.0.1
  "@types/react": 19.2.17
  "@testing-library/react": 16.3.2
  react: 19.2.7
  react-dom: 19.2.7
  react-test-renderer: 19.2.7
  "@types/react-dom": 19.2.3
  "@vitejs/plugin-react": 6.0.3
minimumReleaseAgeExclude:
  - vite-plugin-solid@2.11.13
