blank_issues_enabled: true
contact_links:
  - name: Ask the community
    url: https://github.com/tabler/tabler-icons/discussions/new
    about: Ask and discuss questions with other Tabler community members.
