blank_issues_enabled: true
contact_links:
  - name: Ask the community
    url: https://github.com/tabler/tabler-icons/discussions/new
    about: Ask and discuss questions with other Tabler community members.
  - name: Report a security vulnerability
    url: https://github.com/tabler/tabler-icons/security/advisories/new
    about: Please report security vulnerabilities privately, not as a public issue.
