name: Validate icons

on: [pull_request]

permissions:
  pull-requests: write

jobs:
  validate:
    if: github.repository == 'tabler/tabler-icons'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Validate icons
        id: validate
        run: pnpm run --silent validate > ./comment-markup.md
        continue-on-error: true

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ./comment-markup.md
          comment_tag: validate
          mode: recreate
